databases:
  - name: cliboard_production
    databaseName: cliboard_production
    user: cliboard
    plan: free

services:
  - type: web
    name: cliboard
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: CLIBOARD_DATABASE_URL
        fromDatabase:
          name: cliboard_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: CLIBOARD_DATABASE_PASSWORD
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
